### PR TITLE
Add decision about how to handle namespaces

### PR DESCRIPTION
**Pull request by Kidswiss**
## Summary

From today's discussion how to handle the namespacing.

## Checklist

- [X] Try to isolate changes into separate PRs (to build a better changelog).
- [X] Categorize the PR by setting a good title and adding one of the labels:
      `change`, `decision`, `requirement/quality`, `requirement/functional`, `dependency`
      as they show up in the changelog
- [X] Link this PR to related issues if applicable.

### CODE REVIEW

**Comment by glrf** [comment]
My 2 cents: I think the decision for the namespacing is solid, but I'm not that happy with just removing an old decision as part of this PR. 

If it's not relevant I'd remove it in an other PR with a clear reasoning why the initial decision was flawed

**Comment by Kidswiss** [comment]
> If it's not relevant I'd remove it in an other PR with a clear reasoning why the initial decision was flawed

Would just a separate commit with an appropriate message in this PR also be okay?

**Comment by glrf** [comment]
> Would just a separate commit with an appropriate message in this PR also be okay?

I can live with it,  but it would be cleaner in a separate PR.

The removal just seems more controversial than the addition. Not all of the reasoning in the older decision is invalid in my opinion.

**Comment by Kidswiss** [comment]
> The removal just seems more controversial than the addition. Not all of the reasoning in the older decision is invalid in my opinion.

That's true... Should I maybe put the old decision in an archive or something?

**Comment by tobru** [comment]
> That's true... Should I maybe put the old decision in an archive or something?

Yes, please preserve the old page and mark it clearly as obsolete. And I'd also urge doing that in a separate PR. This here feels like something different / new.

**Review by tobru — CHANGES_REQUESTED** [review]
The current title of this page is a bit too generic IMHO, it's specifically about where to deploy the service to. I'd even argue to add a third option: "Dedicated Service Cluster" (like we do on SPKS) - although I'm not 100% sure. At least it wouldn't affect the decision, with that, I'm happy :+1:

**Comment by Kidswiss** [comment]
> At least it wouldn't affect the decision, with that, I'm happy 👍

That's true. Service clusters would be something different.

**Review by tobru — APPROVED** [review]

**Review by glrf — APPROVED** [review]

**Pull request merged**
