### PR TITLE
Fix links in quality requirements

### PR DESCRIPTION
**Pull request by Kidswiss**
## Summary

This fixes the broken link in #22.

## Checklist

- [x] Try to isolate changes into separate PRs (to build a better changelog).
- [x] Categorize the PR by setting a good title and adding one of the labels:
      `change`, `decision`, `requirement/quality`, `requirement/functional`, `dependency`
      as they show up in the changelog
- [x] Link this PR to related issues if applicable.

### CODE REVIEW

**Review by ccremer — COMMENTED** [review]
I think we agreed to drop this requirement since it's the basically same as https://kb.vshn.ch/app-catalog/reference/quality-requirements/usability/api-declarative.html.

Besides, in #19 I fixed the link in 2da79bd71c6e39d3ae32340fe84a822fee4f27e1

**Comment by Kidswiss** [comment]
https://github.com/vshn/application-catalog-docs/commit/2da79bd71c6e39d3ae32340fe84a822fee4f27e1 Fixes the link for "Automated Provisioning of a Service", but there's also a broken link "Common Interface to Provision Services".

So then I propose we just remove it?

**Comment by ccremer** [comment]
I'd say let's fix the broken link in this PR (cherry-pick https://github.com/vshn/application-catalog-docs/commit/2da79bd71c6e39d3ae32340fe84a822fee4f27e1) and remove the "Common Interface to Provision Services". link & page.

The other PR might stay open for a while.

**Comment by Kidswiss** [comment]
Done, can you quickly crosscheck if everything is okay?

**Review by ccremer — APPROVED** [review]

**Pull request merged**
